name: MCDiscordBridge
main: sex.yakut.mcdiscordbridge.MCDiscordBridge
version: 1.0.0
api-version: 1.8
author: yakut
description: Minecraft → Discord Webhook Bridge
commands:
  mdb:
    description: MCDiscordBridge komutları
    permission: mcdiscordbridge.admin
